# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'verify'
    options: '-DskipTests=true'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  displayName: Docker build
  inputs:
    containerRegistry: 'Docker-Connect'
    repository: 'sathishjatdot'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  displayName: Docker Push
  inputs:
    containerRegistry: 'Docker-Connect'
    repository: 'sathishjatdot'
    command: 'push'
    tags: latest