apiVersion: apps/v1
kind: Deployment
metadata:
  name: sathish-config-server-pod
  namespace: sathishproject
spec:
    replicas: 1
    selector:
      matchLabels:
        app: sathish-config-server
    template:
      metadata:
        labels:
          app: sathish-config-server
      spec:
        containers:
          - name: sathish-config-server-container
            image: travelhelper0h/sathishproject-config-server:latest
            ports:
              - containerPort: 8888
            imagePullPolicy: IfNotPresent
            env:
              - name: JAR_FILE
                value: "application.jar"
              - name: APP_PORT
                value: "8888"
              - name: GIT_URI
                value: "https://github.com/sathishjayapal/jubilant-memory.git"
              - name: encrypt_key
                value: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAK8GMsEw44Vw71MsofkIaS5PWKVP1A2yNCxoXNP31VEi4gCUt2ViRkan/c4/WXW7eAOP07Qh7Z287TfZFbgH2oNpVBakuTo5VdmpknZ3z89I4ah36l3+DwaY7JuSSVl0KzDs/xXesmJxBU8gxtNh9AzTvYxuR4bTGPZDMVJuBQ9nAgMBAAECgYAoxQbZnavCD7aP51uriNwHX5BEob3BmvswRPcqoRZdmgSPIhU+VpAMMWGbw4HxPMQOAFjOIwEYt0OCuNyoS5wIkJwYpu5skP5dZ02+TnzZ4LQpEIyLWZtK2BVK/PXTGmMh0zYBE4Ruvx4pwfb0A0nltzY5H5yCR72QMnZloR/T0QJBAPb5MDkobGB19rUezSxUAuCQeLEmdmH5BHD71jtS/EaPCKGkp4ifZ/SO5N8JibyN5MLZ/dDZ51GOWOY4LTn9hbsCQQC1a9DfBVvtJlgtg+aITZwV+rHLKlVP141RbOmoYWJwrubja4fmkQuqXJNfeei3LQ6XclvXHujq9LLCpvlo7cxFAkEAxusDlTXivHqmn1DUrhxoSNjz7LLu7JA1rI6aCSQYvvfbWt4Udez2PLqOyrmS74RVuT78uKeZMU32ek7K1odEmwJBALR8SXTGURjSD+FgGoW5qDHZkO2M9QiUafv6vU4NbDCsX/kaLj58SD25EchncNRjF+QlG
              - name: username
                value: "sathish"
              - name: pass
                value: "pass"
