apiVersion: apps/v1
kind: Deployment
metadata:
  name: sathish-config-server-pod
spec:
    replicas: 1
    selector:
      matchLabels:
        app: sathish-config-server
    template:
      metadata:
        labels:
          app: sathish-config-server
      spec:
        containers:
          - name: sathish-config-server-container
            image: travelhelper0h/config-server:latest
            imagePullPolicy: Always
            env:
              - name: JAR_FILE
                value: "config-server.jar"
              - name: APP_PORT
                value: "8888"
              - name: GIT_URI
                value: "https://github.com/sathishjayapal/jubilant-memory.git"

