version: '3.8'
services:
  # RabbitMQ service engine
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
  # conductor related service
  conduktor-console:
    image: conduktor/conduktor-console:1.24.0
    hostname: sathishconduktor-console
    container_name: sathishconduktor-console
    ports:
      - "9080:9080"
    volumes:
      - type: bind
        source: "./config.yaml"
        target: /opt/conduktor/config.yaml
        read_only: true
      - conduktor_data:/var/conduktor
    environment:
      CDK_IN_CONF_FILE: /opt/conduktor/config.yaml
      CDK_LISTENING_PORT: "9080"
      CDK_DATABASE_URL: "postgresql://psqladmin:psqladminpas$@1testsathisprj1postgres.postgres.database.azure.com:5432/conduktor-console"
      CDK_CLUSTERS_0_ID: "sathish-local-kafka"
      CDK_CLUSTERS_0_NAME: "sathish-local-kafka"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "192.168.5.68:9092"
      CDK_CLUSTERS_0_COLOR: "#6A57C8"
      CDK_CLUSTERS_0_ICON: "kafka"
      CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
      CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
      CDK_MONITORING_CALLBACK-URL: http://conduktor-console:9080/monitoring/api/
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:9080
  conduktor-monitoring:
    image: conduktor/conduktor-console-cortex:1.24.0
    environment:
      CDK_CONSOLE-URL: "http://sathishconduktor-console:9080"
volumes:
  conduktor_data: {}
  rabbitmq_data:  {}
  rabbitmq_log: {}
